### ISSUE TITLE
Erste Sekunden des Videos werden verschluckt

### ISSUE THREAD

**Issue by laclaro** [prof-membrane/plugin.video.wdrmediathek#7]
Hallo,

vielen Dank für die gute Arbeit an den Mediatheken. Mir ist aufgefallen, dass beim Starten der Videos die ersten paar Sekunden des Videos verschluckt werden. Kann man vielleicht eine Puffer-Verzögerung oder soetwas einbauen, damit das nicht mehr passiert?

Viele Grüße

Henning

**Comment by prof-membrane** [comment]
Damit haben meine Add-ons nichts zu tun. Das ist Sache von Kodi.
